import jsPDF from 'jspdf'
import { saveAs } from 'file-saver'

/**
 * Copy text to clipboard
 * @param {string} text - Text to copy
 * @returns {Promise<boolean>} Success status
 */
export async function copyToClipboard(text) {
    try {
        await navigator.clipboard.writeText(text)
        return true
    } catch (error) {
        console.error('Failed to copy to clipboard:', error)
        // Fallback method
        try {
            const textArea = document.createElement('textarea')
            textArea.value = text
            textArea.style.position = 'fixed'
            textArea.style.left = '-999999px'
            document.body.appendChild(textArea)
            textArea.select()
            document.execCommand('copy')
            document.body.removeChild(textArea)
            return true
        } catch (fallbackError) {
            console.error('Fallback copy failed:', fallbackError)
            return false
        }
    }
}

/**
 * Download text as TXT file
 * @param {string} text - Text content
 * @param {string} filename - Optional filename (default: snapnotes-{timestamp}.txt)
 */
export function downloadTXT(text, filename = null) {
    const name = filename || `snapnotes-${Date.now()}.txt`
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' })
    saveAs(blob, name)
}

/**
 * Download notes as PDF file
 * @param {string} text - Text content
 * @param {string} format - Note format (bullet, qa, flashcard)
 * @param {string} filename - Optional filename (default: snapnotes-{timestamp}.pdf)
 */
export function downloadPDF(text, format = 'bullet', filename = null) {
    const name = filename || `snapnotes-${Date.now()}.pdf`

    // Create new PDF document
    const doc = new jsPDF()

    // Add title
    doc.setFontSize(20)
    doc.setFont('helvetica', 'bold')
    doc.text('SnapNotes AI', 20, 20)

    // Add metadata
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(100)
    doc.text(`Format: ${format.toUpperCase()} | Generated: ${new Date().toLocaleDateString()}`, 20, 28)

    // Add separator line
    doc.setDrawColor(200)
    doc.line(20, 32, 190, 32)

    // Add content
    doc.setFontSize(11)
    doc.setTextColor(0)
    doc.setFont('helvetica', 'normal')

    // Split text into lines and add to PDF
    const lines = doc.splitTextToSize(text, 170) // 170mm width for margins
    let yPosition = 40

    lines.forEach((line) => {
        // Check if we need a new page
        if (yPosition > 280) {
            doc.addPage()
            yPosition = 20
        }

        doc.text(line, 20, yPosition)
        yPosition += 6
    })

    // Add footer on last page
    const pageCount = doc.internal.getNumberOfPages()
    doc.setPage(pageCount)
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text('Generated by SnapNotes AI - Powered by Tambo AI', 105, 290, { align: 'center' })

    // Save the PDF
    doc.save(name)
}

/**
 * Format text for export based on format type
 * @param {string} text - Raw text
 * @param {string} format - Format type
 * @returns {string} Formatted text
 */
export function formatTextForExport(text, format) {
    const timestamp = new Date().toLocaleString()
    const header = `SnapNotes AI - ${format.toUpperCase()} Notes\nGenerated: ${timestamp}\n${'='.repeat(50)}\n\n`

    return header + text
}

export default {
    copyToClipboard,
    downloadTXT,
    downloadPDF,
    formatTextForExport,
}
